# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --debug
      - run: flutter build ios --debug --no-codesign
      - uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/apk/debug/*.apk"
         artifacts: "build/ios/iphoneos/*.app."
         token: ${{ secrets.GH_TOKEN }}
         tag: "1.1.0"
         commit: ${{ github.sha }}
